### ISSUE TITLE
Error occurs on the Absence/Presence page if the column "Protein.Ids" is missing

### ISSUE THREAD

**Issue by Hailey-Z** [MonashProteomics/FragPipe-Analyst#103] opened 2024-12-17 23:49 UTC
The following line introduces errors on the Absence/Presence page

https://github.com/MonashProteomics/FragPipe-Analyst/blame/4a384a1753f264f3e3ed3d0a8bfe895510a1021f/server.R#L1733

**Comment by hsiaoyi0504** [comment] 2024-12-19 03:28
Still checking.  Protein.Ids should be there if it's generated by FragPipe. Asked in Nesvilab/FragPipe-Analyst#64

**Comment by HibaSALIM** [comment] 2024-12-19 08:08
We are using the version 1.9.2 of DIANN, and we noticed that the generated file does not include the protein.ids column. The same issue occurs with DIANN version 1.9. However, when using DIANN version 1.8.2, the protein.ids column is present. It appears that this column is no longer generated in the newer versions of DIANN.

**Comment by hsiaoyi0504** [comment] 2024-12-19 13:40
@HibaSALIM Thanks for letting us know. I updated the dev server to v1.9 to support this case. Please try and let us know if there is still any issue. Thanks.

@Hailey-Z Can you also update the production server to v1.9. Thanks.

**Comment by vdemichev** [comment] 2024-12-19 13:51
1.9.2 definitely has Protein.Ids in the main .parquet report, can you please double check?

**Comment by vdemichev** [comment] 2024-12-19 13:51
1.9.2 definitely has Protein.Ids in the main .parquet report, can you please check again?

**Comment by HibaSALIM** [comment] 2024-12-19 15:19
Here’s a clearer and more polished version:
________________________________
Dear All,
Thank you very much for your efforts. I’m pleased to share that everything is now working well, and I can successfully obtain the Absence/Presence table. Regarding the .parquet report, we are not able to upload it to the website as we require the pg-matrix file for our analysis.
I do have two additional questions about Fragpipe Analyst, and I hope you can assist with them:

  1.
Correct Parameter Information: The report.pdf file generated by Fragpipe Analyst does not include accurate details about the parameters used for statistical analysis (e.g., imputation, LFQ, etc.). Is there a way to ensure the correct parameters are included in the PDF? Alternatively, could it be possible to generate a .log file that contains all the parameter details used for statistical analysis? This would be extremely helpful for future reference when revisiting the results.
  2.
Paired Statistical Analysis: Is there an option to perform paired statistical analyses in Fragpipe Analyst? For example, comparing data from the same patients before and after a specific treatment.

Thank you very much for your time and consideration. I truly appreciate your support and guidance on these matters.
Best regards,
Hib




[cid:4af181e5-9013-4fb5-8af9-0849efe0d8fd]


Hiba Salim, PhD

Postdoctoral researcher


Centre for Genomic Regulation (CRG)
Carrer Dr. Aiguader 88
08003 Barcelona, Spain

________________________________

**Comment by hsiaoyi0504** [comment] 2024-12-19 17:17
@HibaSALIM Yes, we could address the other requests but it might take some times.
@vdemichev I think the user is talking about protein group matrix but not the .parquet report.

**Comment by vdemichev** [comment] 2024-12-19 17:19
This is by design then, as protein ids list is precursor-specific and not protein group-specific, i.e. reporting it previously in the matrix was basically a bug.

**Comment by hsiaoyi0504** [comment] 2024-12-19 17:21
@vdemichev Thanks for clarifying that!
@HibaSALIM For the requests: 
> 1. Correct Parameter Information: The report.pdf file generated by Fragpipe Analyst does not include accurate details about the parameters used for statistical analysis (e.g., imputation, LFQ, etc.). Is there a way to ensure the correct parameters are included in the PDF? Alternatively, could it be possible to generate a .log file that contains all the parameter details used for statistical analysis? This would be extremely helpful for future reference when revisiting the results.

Will be addressed in #104.

> 2. Paired Statistical Analysis: Is there an option to perform paired statistical analyses in Fragpipe Analyst? For example, comparing data from the same patients before and after a specific treatment.

Please keep eyes on #96. @Hailey-Z Is there any update?

**Closed by hsiaoyi0504** 2024-12-19 17:21 UTC
Labels: bug

**Comment by HibaSALIM** [comment] 2025-01-28 14:32
Dear all,

I hope this email finds you well.
I’m reaching out to inquire about the status of issue #96, which pertains to the possibility of performing paired statistical analyses in Fragpipe Analyst. Are there any updates or planned developments on this feature in the near future?
Thank you for your time and support!
Best regards,
Hiba Salim


[cid:d545a646-2d16-49af-a158-1fe694a053db]


Hiba Salim, PhD

Postdoctoral researcher


Centre for Genomic Regulation (CRG)
Carrer Dr. Aiguader 88
08003 Barcelona, Spain

________________________________
